BACKEND_DEVELOPER = {
    "required": [
        "Python",
        "FastAPI",
        "Flask",
        "REST API",
        "SQL",
        "PostgreSQL",
        "MySQL",
        "Git",
        "GitHub",
        "Linux",
        "Docker",
        "Object-Oriented Programming",
    ],

    "optional": [
        "Django",
        "Redis",
        "MongoDB",
        "RabbitMQ",
        "Celery",
        "GraphQL",
        "JWT",
        "OAuth",
        "Nginx",
        "CI/CD",
        "AWS",
        "Azure",
        "GCP",
        "Microservices",
        "PyTest",
        "Kubernetes",
    ],
}