DATA_SCIENTIST = {
    "required": [
        "Python",
        "SQL",
        "Pandas",
        "NumPy",
        "Statistics",
        "Machine Learning",
        "Data Analysis",
        "Data Visualization",
        "Scikit-learn",
        "Jupyter",
    ],

    "optional": [
        "Deep Learning",
        "TensorFlow",
        "PyTorch",
        "Artificial Intelligence",
        "NLP",
        "Computer Vision",
        "Git",
        "GitHub",
        "Power BI",
        "Tableau",
        "Matplotlib",
        "Seaborn",
        "Plotly",
        "PostgreSQL",
        "MySQL",
        "AWS",
        "Docker",
        "Linux",
    ],
}