FULLSTACK_DEVELOPER = {
    "required": [
        "HTML",
        "CSS",
        "JavaScript",
        "TypeScript",
        "React",
        "Node.js",
        "Express.js",
        "REST API",
        "Python",
        "FastAPI",
        "SQL",
        "PostgreSQL",
        "Git",
        "GitHub",
        "Docker",
    ],

    "optional": [
        "Next.js",
        "Angular",
        "Vue.js",
        "Redux",
        "Tailwind CSS",
        "Bootstrap",
        "MongoDB",
        "Redis",
        "JWT",
        "OAuth",
        "GraphQL",
        "AWS",
        "Azure",
        "GCP",
        "Kubernetes",
        "CI/CD",
        "Linux",
        "Nginx",
        "Microservices",
        "PyTest",
        "Jest",
        "Cypress",
    ],
}