ML_ENGINEER = {
    "required": [
        "Python",
        "SQL",
        "Pandas",
        "NumPy",
        "Machine Learning",
        "Deep Learning",
        "Scikit-learn",
        "TensorFlow",
        "PyTorch",
        "Statistics",
        "Git",
        "Linux",
    ],

    "optional": [
        "Artificial Intelligence",
        "NLP",
        "Computer Vision",
        "MLOps",
        "Docker",
        "Kubernetes",
        "AWS",
        "Azure",
        "GCP",
        "FastAPI",
        "Flask",
        "Jupyter",
        "PostgreSQL",
        "MySQL",
        "CI/CD",
    ],
}