PYTHON_DEVELOPER = {
    "required": [
        "Python",
        "Git",
        "GitHub",
        "SQL",
        "PostgreSQL",
        "MySQL",
        "FastAPI",
        "Flask",
        "REST API",
        "Object-Oriented Programming",
        "Debugging",
        "Linux",
    ],

    "optional": [
        "Django",
        "Docker",
        "Redis",
        "MongoDB",
        "PyTest",
        "CI/CD",
        "AWS",
        "Azure",
        "GCP",
        "Celery",
        "RabbitMQ",
        "GraphQL",
        "Jupyter",
        "Pandas",
        "NumPy",
        "JSON",
        "YAML",
        "Microservices",
    ],
}